name = "HubbardTN"
uuid = "31f8dd75-9f76-4da8-9aed-ce20a80dcd69"
version = "0.3.0"
authors = ["Daan Vrancken"]

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JLD2 = "0.6"
KrylovKit = "0.10"
MPSKit = "0.13"
MPSKitModels = "0.4"
TensorKit = "0.14, 0.15, 0.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
